[package]
name = "compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
bytecode = { path = "../bytecode" }
clap = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
